### ISSUE TITLE
3.2.4.4 - 3.2.4.7

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2015Tim7#18]
3.2.4.4 - 3.2.4.7 trebaju ići zajedno. Nema potrebe da se ovako razbijaju i vežu.

**Comment by anogo1** [comment]
Pošto su 3.2.4.1 i 3.2.4.2 spojeni zajedno, zaključio sam da bi i 3.2.4.3 trebao ići zajedno sa 3.2.4.4 - 3.2.4.7 , pa su svi spojeni u jednu cjelinu
