### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by spica29** [SoftverInzenjeringETFSA/SI2015Tim7#25]
commit ID:
03493edd8710d6993036f1a50f63e12df438aed8

Opis problema:
Login sa usernameom i passwordom iz baze ne radi.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju App.java ili bilo koji drugi View (svaki zahtjeva login).
2. Unos u login vrijednosti kolona username i password iz baze, tabela Osoba
3. Kliknuti Login

Dobijeni rezultat:
- Prikaze se JOptionPane sa greškom o pogrešnim pristupnim podacima.
  http://pokit.org/get/?46c635c110e57b77e41184ed53527b23.jpg

Očekivani rezultat:
- Očekuje se uspješno logiranje

**Comment by ajdinm** [comment]
Passwordi su heširani, originalne passworde mozes naci u klasi vozniPark/src/main/java/vozniPark/Util/PopuniBazu.java.
