### ISSUE TITLE
Spremanje nove vožnje - preuzimanje vozila

### ISSUE THREAD

**Issue by admirah** [SoftverInzenjeringETFSA/SI2015Tim7#26]
Komponenta:
Vozni Park

commit ID:
03493ed

Opis problema:
U polje se unosi datum i vrijeme preuzimanja dok se u bazu uvijek sprema trenutno vrijeme.

Koraci za reproduciranje problema:
1. Login kao vozac
2. Odabrati broj registarske tablice
3. Unijeti datum
4. Unijeti vrijeme
5. Kliknuti prijavi

Dobijeni rezultat:
 U bazi  u tabeli voznje, u koloni DATUMPREUZIMANJA je uneseno trenutno vrijeme

Screenshot:
http://prntscr.com/b4scji
http://prntscr.com/b4sd8z

Očekivani rezultat:
U bazi  u tabeli voznje, u koloni DATUMPREUZIMANJA je uneseno vrijeme sa forme

**Comment by IrmaKarasoftic** [comment]
Fixed, commit ID: 1ee393987c9928733bb141e30e3286da7fdcab4f
