### ISSUE TITLE
Validacija za vrijeme ne postoji

### ISSUE THREAD

**Issue by admirah** [SoftverInzenjeringETFSA/SI2015Tim7#28]
Komponenta:
Vozni Park 

commit ID:
03493ed

Opis problema:
Moguće je unijeti nevalidno vrijeme ( sati i minuti izvan opsega) 

Koraci za reproduciranje problema:
1. Login kao vozac
2. Unijeti neispravno vrijeme u polje
3. Pritisnuti button Prijavi

Screenshot:
http://prntscr.com/b4si3x

Dobijeni rezultat:
Prijava preuzimanja vozila prosla bez greške

Očekivani rezultat:
Grešku za nevalidno vrijeme

**Comment by anogo1** [comment]
#27
