### ISSUE TITLE
ERD dijagram (neusaglasenost koda i dizajna)

### ISSUE THREAD

**Issue by spica29** [SoftverInzenjeringETFSA/SI2015Tim7#29]
commit ID:
811c939659ad3b86f49165383a4267de532d3022

Opis problema:
neusaglašenost dizajna i koda (erd)

Koraci za reproduciranje problema:
1. Provjeriti erd u dokumentaciji na 
https://github.com/SoftverInzenjeringETFSA/SI2015Tim7/blob/master/Dokumentacija/UIS-CodeDoc.pdf i kod koji je generisan u bazi

Dobijeni rezultat:
ERD dijagram nije isti kao u specifikaciji dizajna
http://pokit.org/get/?7726ff2a0f6e45cd61c8ad3dce4a5ff6.jpg
http://pokit.org/get/?68a1ecfbc64c6a6ab4c3a326e456f150.jpg

**Comment by ajdinm** [comment]
Ispravka zahtjeva promjenu SRSa, sto u ovoj fazi nije moguće.
