### ISSUE TITLE
Neispravna validacija registracije pri unosu vozila

### ISSUE THREAD

**Issue by admirah** [SoftverInzenjeringETFSA/SI2015Tim7#33]
commit ID:
03493ed

Opis problema:
Nemogućnost dodavanja vozila- razlog nevalidan format registracije, iako je ispravan

Koraci za reproduciranje problema:
1. Login kao šef
2. Klik na dugme Unesi vozilo
3. Unijeti validan format registracije

Screenshot:
http://prnt.sc/b4sw2k

Dobijeni rezultat:
Nemogućnost dodavanja vozila

Očekivani rezultat:
Uspješno dodavanje vozila

**Comment by anogo1** [comment]
registracija nije unesena pravilno, as0000000 ne treba da se prihvati kao validan unos
