### ISSUE TITLE
Unhandled exception za generisanje izvještaja o aktivnostima vozača ako nisu navedeni parametri

### ISSUE THREAD

**Issue by admirah** [SoftverInzenjeringETFSA/SI2015Tim7#40]
Komponenta:
Vozni park

commit ID:
03493ed

Opis problema:
Ukoliko pritisnemo button za generisanje izvještaja dolazi do bacanja izuzetka ako nisu navedeni parametri

Koraci za reproduciranje problema:
1. Login kao sef
2. Klik na button Izvještaji 
3. Odabrati Izvještaji o aktivnostima vozača

Screenshot:
http://prnt.sc/b4tdfw

Dobijeni rezultat:
Unhandled exception

Očekivani rezultat:
Greška

**Comment by ajdinm** [comment]
http://pokit.org/get/img/bec9c9dd2bfb16c898f99a34916a3a8a.png
Unable to reproduce, moze li vise informacija u exeptionu ? Mozda da postavis citav tekst exceptiona ?

**Comment by admirah** [comment]
Ovako sad sam ponovo testirala. Kad tek pokrenem aplikaciju, znaci nikakvih aktivnosti ako nema desi se to kao kod tebe. Međutim ja sam otvorila izvještaje nakon što sam prijavljivala vožnje, nisam mogla da skontam da je potrebna neka akcija prije toga da bi se desio. 
Exception koji se javi je ovaj. Znači 
1.Login kao vozač
2. Izvršiti prijavu vožnje
3. Login kao sef
4 Klik na button Izvještaji 
5. Odabrati Izvještaji o aktivnostima vozača

http://pastebin.com/sQV48pXp

**Comment by admirah** [comment]
Isti slučaj sa onim drugim bugom oko ovog izvještaja. Znači invalid definitivno nije.

**Comment by anogo1** [comment]
sa ovako navedenim koracima, ovo predstavlja posljedicu već navedenog issue-a #34, dakle problem je u prijavljivanju vožnje
