### ISSUE TITLE
Unhandled exception za generisanje izvještaja o aktivnostima vozača ako su navedeni parametri

### ISSUE THREAD

**Issue by admirah** [SoftverInzenjeringETFSA/SI2015Tim7#41]
Komponenta:
Vozni park

commit ID:
03493ed

Opis problema:
Ukoliko pritisnemo button za generisanje izvještaja dolazi do bacanja izuzetka su navedeni parametri 

Koraci za reproduciranje problema:
1. Login kao šef
2. Klik na button Izvještaji 
3. Odabrati Izvještaji o aktivnostima vozača
4. Unijeti polja
5. Klik na Prikaži

Screenshot:
http://prntscr.com/b4tg9h

Dobijeni rezultat:
Unhandled exception

Očekivani rezultat:
Javiti grešku da vozač ne postoji ako zadani parametri nisu ispravni ili prikazati izvještaj ako jesu

**Comment by ajdinm** [comment]
Unable to reproduce. 
http://pokit.org/get/img/e3c9345c30a418bdaa12cd74bd6e2408.png

**Comment by anogo1** [comment]
identično kao issue #40 
(ova dva issue-a su mogla biti spojena u jedan, pošto nije problem u tome da li su uneseni parametri ili ne)
