### ISSUE TITLE
Mogućnost unosa nelogičnih podataka za Ime i Prezime vozača

### ISSUE THREAD

**Issue by admirah** [SoftverInzenjeringETFSA/SI2015Tim7#42]
commit ID:
03493ed

Opis problema:
Moguće unijeti nelogične podatke za ime i prezime korisnika

Koraci za reproduciranje problema:
1. Login kao šef
2. Klik na unesi vozača
3. Popuniti polja sa nelogičnim vrijednostima za ime i prezime
4. Kliknuti Registruj vozača

Dobijeni rezultat:
Vozač registrovan

Screenshot:
http://prntscr.com/b4tlqg

Očekivani rezultat:
Prijava o greški

**Comment by IrmaKarasoftic** [comment]
Rijeseno u commit ID: d4806efbbd1a9d27748283d5c2845fed2ef49110
Ispravka referencirana u issue-u #72 koji je zapravo duplikat.
