### ISSUE TITLE
Problemi vezani za prijavu vozila na Servis ( vise issua u jedno )

### ISSUE THREAD

**Issue by admirah** [SoftverInzenjeringETFSA/SI2015Tim7#47]
Komponenta:
Vozni park

commit ID:
03493ed

Opis problema1:
Nevalidiran datum i vrijeme ( može se unijeti bilo šta )
Opis problema 2:
U bazu se unosi trenutno vrijeme bez obzira sta je navedeno u poljima datum i vrijeme
Opis problema 3
Istvoremeno se unosi i datum vracanja iako automobil nije vracen

Koraci za reproduciranje problema:
1. Login kao šef
2. Klik na button Servisi
3. Na tabu Prijava vozila na servis unijeti datume 
4. Odabrati vozilo
5. Klik na Potvrdi

Screenshot:
http://prntscr.com/b4uj2k - unos 
http://prntscr.com/b4ujvl - iz baze

Dobijeni rezultat:
Unos servisa uspješno spremljen, Vrijeme odlaska i vrijeme vraćanja postavljeni na trenutno vrijeme

Očekivani rezultat:
Javiti grešku za nevalidan datum i vrijeme
U bazu unijete uneseno vrijeme
U bazu ne unositi datum vraćanja

**Comment by anogo1** [comment]
datum vraćanja se pri prijavi postavlja na isti datum kao datum prijavljivanja, te se isti mijenja tek kada se vozilo vrati sa servisa(ista stvar se radi sa opisom servisa)
