### ISSUE TITLE
Unhandled exception za prijavu preuzetog vozila ako nisu uneseni parametri

### ISSUE THREAD

**Issue by lbajgoric1** [SoftverInzenjeringETFSA/SI2015Tim7#59]
Komponenta: 
Prijavljivanje preuzetog vozila

commit ID:
a029d30fc6102edcc447873f6f608c234d41af2c

Opis problema:
Ako pritisnemo dugme _Prijavi_ za prijavu preuzetog vozila dolazi do bacanja izuzetka ako nisu uneseni parametri.

Koraci do reproduciranja problema:
1. Login kao vozac
2. Klik na dugme _Prijava preuzetog vozila_ 
3. Klik na dugme _Prijavi_ 

Dobijeni rezultat:
Exception (Screenshot: http://prntscr.com/b55tr1)

Ocekivani rezultat:
- Ocekuje se poruka da je potrebno unijeti parametre kako bi se zavrsila prijava

**Comment by anogo1** [comment]
#58
