### ISSUE TITLE
Unhandled exception za odjavljivanje preuzetog vozila

### ISSUE THREAD

**Issue by lbajgoric1** [SoftverInzenjeringETFSA/SI2015Tim7#60]
Komponenta: 
- Odjavljivanje preuzetog vozila

commit ID:
a029d30

Opis problema:
Ako pritisnemo dugme _Odjavi vozilo_ za odjavu preuzetog vozila dolazi do bacanja izuzetka ako su uneseni neispravni parametri

Koraci do reproduciranja problema:
1. Login kao vozac
2. Klik na dugme _Odjava preuzetog vozila_ 
3. Unos neispravnih parametara za polja _Datum vracanja, Vrijeme vracanja, Broj predjenih kilometara, Opis koristenja vozila_.
4. Klik na dugme _Odjavi vozilo_

Dobijeni rezultat:
- Exception (Screenshot: http://prntscr.com/b56bry)

Ocekivani rezultat:
- Ocekuje se poruka o neispravnosti parametara

**Comment by anogo1** [comment]
#50
