### ISSUE TITLE
Labela Cijena goriva nije citava vidljiva

### ISSUE THREAD

**Issue by lbajgoric1** [SoftverInzenjeringETFSA/SI2015Tim7#61]
Komponenta: 
- Odjavljivanje preuzetog vozila

commit ID:
a029d30

Opis problema:
Ako pritisnemo dugme _Odjavi vozilo_ za odjavu preuzetog vozila labela _Cijena goriva_ nije potpuno vidljiva

Koraci do reproduciranja problema:
1. Login kao vozac
2. Klik na dugme _Odjava preuzetog vozila_ 

Dobijeni rezultat:
- Labela _Cijena goriva_ koja nije potpuno vidljiva (Screenshot: http://prntscr.com/b56fsl)

Ocekivani rezultat:
- Labela _Cijena goriva_ koja je potpuno vidljiva

**Comment by anogo1** [comment]
besmislen bug
