### ISSUE TITLE
Moguce modifikovati tabelu Pregled vozaca

### ISSUE THREAD

**Issue by lbajgoric1** [SoftverInzenjeringETFSA/SI2015Tim7#62]
Komponenta: 
- Pregled vozaca

commit ID:
a029d30

Opis problema:
Polja u tabeli koja se nalazi na formi _Pregled vozaca_ je moguce modifikovati.

Koraci do reproduciranja problema:
1. Login kao sef
2. Klik na dugme _Pregled vozaca_
3. Dvoklik bilo kojeg polja tabele i modifikovanje sadrzaja polja

Dobijeni rezultat:
- Tabela sa modifikovanim sadrzajem (Screenshot: http://prntscr.com/b56ka4)

Ocekivani rezultat:
- Tabela u kojoj nije omoguceno modifikovanje sadrzaja polja

**Comment by anogo1** [comment]
Sva eventualna modifikovanja su samo trenutna, same vrijednosti koje su prikazane u tim poljima nisu modifikovane, te se ne mijenjaju. Sve vrijednosti će ponovo biti prikazane na najnormalniji način ukoliko se ponovo otvori određeni izvještaj ili tabela.
