### ISSUE TITLE
Prozor za pregled vozila ostaje otvoren

### ISSUE THREAD

**Issue by lbajgoric1** [SoftverInzenjeringETFSA/SI2015Tim7#63]
Komponenta: 
- Pregled slobodnih vozila

commit ID:
a029d30

Opis problema:
Ako pritisnemo dugme _Pregled slobodnih vozila_, u slucaju kada nema slobodnih vozila, nakon obavijesti prozor _Pregled slobodnih vozila_ ostaje otvoren.

Koraci do reproduciranja problema:
1. Login kao sef
2. Klik na dugme _Pregled slobodnih vozila_

Dobijeni rezultat:
- Prozor _Pregled slobodnih vozila_ ostaje otvoren (kada nema slobodnih vozila)
  (Screenshot:
  [http://prntscr.com/b56t4k](url) [http://prntscr.com/b56tew](url) )

Ocekivani rezultat:
- Prozor _Pregled slobodnih vozila_ se zatvara nakon poruke da nema slobodnih vozila.

**Comment by anogo1** [comment]
Nema potrebe za porukom da nema slobodnih vozila, pošto će tabela koja prikazuje slobodna vozila biti prazna u koliko istih nema.(Nigdje nije specificirano da će doći do zatvaranja forme ukoliko nema slobodnih vozila.)
