### ISSUE TITLE
Moguce modifikovati tabelu pregled slobodnih vozila

### ISSUE THREAD

**Issue by lbajgoric1** [SoftverInzenjeringETFSA/SI2015Tim7#64]
Komponenta: 
- Pregled slobodnih vozila

commit ID:
a029d30

Opis problema:
Polja u tabeli koja se nalazi na formi _Pregled slobodnih vozila_ je moguce modifikovati.

Koraci do reproduciranja problema:
1. Login kao sef
2. Klik na dugme _Pregled slobodnih vozila_
3. Dvoklik bilo kojeg polja tabele i modifikovanje sadrzaja polja

Dobijeni rezultat:
- Tabela sa modifikovanim sadrzajem (Screenshot: http://prntscr.com/b57cuh)

Ocekivani rezultat:
- Tabela u kojoj nije omoguceno modifikovanje sadrzaja polja

**Comment by anogo1** [comment]
#62 
isti problem je opisan, samo na drugom mjestu
