### ISSUE TITLE
Moguce modifikovati tabelu izvjestaj o odabranom vozilu

### ISSUE THREAD

**Issue by lbajgoric1** [SoftverInzenjeringETFSA/SI2015Tim7#65]
Komponenta: 
- Izvjestaj o odabranom vozilu

commit ID:
a029d30

Opis problema:
Polja u tabeli koja se nalazi na formi _Izvjestaj o odabranom vozilu_ je moguce modifikovati.

Koraci do reproduciranja problema:
1. Login kao sef
2. Klik na dugme _Izvjestaji_
3. Klik na dugme _Izvjestaj o odabranom vozilu_
3. Dvoklik bilo kojeg polja tabele i modifikovanje sadrzaja polja

Dobijeni rezultat:
- Tabela sa modifikovanim sadrzajem (Screenshot: http://prntscr.com/b57l7p)

Ocekivani rezultat:
- Tabela u kojoj nije omoguceno modifikovanje sadrzaja polja

**Comment by anogo1** [comment]
#62 
isti problem je opisan, samo na drugom mjestu
