### ISSUE TITLE
Moguce modifikovati tabelu izvjestaj o servisima svih vozila 

### ISSUE THREAD

**Issue by lbajgoric1** [SoftverInzenjeringETFSA/SI2015Tim7#66]
Komponenta:
- Izvjestaj o servisima svih vozila

commit ID:
a029d30

Opis problema:
Polja u tabeli koja se nalazi na formi Izvjestaj o servisima svih vozila je moguce modifikovati.

Koraci do reproduciranja problema:
1. Login kao sef
2. Klik na dugme Izvjestaji
3. Klik na dugme Izvjestaj o servisima svih vozila
3. Dvoklik bilo kojeg polja tabele i modifikovanje sadrzaja polja

Dobijeni rezultat:
- Tabela sa modifikovanim sadrzajem (Screenshot: http://prntscr.com/b57nll)

Ocekivani rezultat:
- Tabela u kojoj nije omoguceno modifikovanje sadrzaja polja

**Comment by anogo1** [comment]
#62 
isti problem je opisan, samo na drugom mjestu
