### ISSUE TITLE
Blank space u textboxu

### ISSUE THREAD

**Issue by fademovic** [SoftverInzenjeringETFSA/SI2015Tim7#70]
Komponenta:
Vozni park

commit ID:
e26a9d8

Opis problema:
Ukoliko polja "naziv vozila" ili "registracija" sadrže _blank space_  na kraju unesenog stringa aplikacija ne prepoznaje o kojem je vozilu riječ

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Vozni park"
2. Logovati se kao šef
3. Kliknuti na "Pregled novih vozila"
4. Unijeti naziv vozila i registraciju

Dobijeni rezultat:
Prazna forma

Očekivani rezultat:
Podaci o vozilu 

![praznomjesto1](https://cloud.githubusercontent.com/assets/16963805/15378311/abf02f36-1d62-11e6-99f2-26959f95a936.PNG)

**Comment by anogo1** [comment]
besmislen bug
