### ISSUE TITLE
Dodani vozač se ne učita u pregledu vozača issue

### ISSUE THREAD

**Issue by spica29** [SoftverInzenjeringETFSA/SI2015Tim7#76]
commit ID: 
e26a9d8053d3050c71a3204378d68e1e86eec2ae

Opis problema:
Dodani vozač se ne učitava u tabeli

Koraci za reproduciranje problema:
1. Login kao šef
2. Otvoriti formu za prikaz vozača i dodavanje vozača
3. Dodati novog vozača http://pokit.org/get/?9d3a93dbc356fde79bb7a669b2104eb1.jpg

Dobijeni rezultat:
Prikaz vozača ostaje isti http://pokit.org/get/?c853ef7629d1002f33a60bfc8b5e00d3.jpg

Očekivani rezultat:
Prikaz novog vozača ili ukidanje mogućnosti da se mogu obje forme imati otvorene u isto vrijeme

**Comment by anogo1** [comment]
ukoliko se forma za prikaz otvori nakon dodanog vozaca, on ce biti prikazan(sto je slucaj sa ovim vozačem "Amela Špica", jedini problem je što nije regulisano zatvaranje formi nakon završetka sa njima, isti problem oko ne zatvaranja formi je opisan u issue #53 (tamo je samo naveden primjer kada se odradi Odjava, forme idalje ostaju otvorene)

**Comment by spica29** [comment]
ja ovdje govorim o mogucnosti istovremenog otvaranja medjusobno zavisnih formi, a tamo o zatvaranju pri odjavi, ali dobroo
