### ISSUE TITLE
Izvještaji - Ispis aktivnosti vozača

### ISSUE THREAD

**Issue by alicajla** [SoftverInzenjeringETFSA/SI2015Tim7#78]
Komponenta: Pregled vozača

Commit ID: [e26a9d8](https://github.com/SoftverInzenjeringETFSA/SI2015Tim7/commit/e26a9d8053d3050c71a3204378d68e1e86eec2ae)  

Opis problema: Program crusha: 
![image](https://cloud.githubusercontent.com/assets/11289675/15427429/5dd33026-1e95-11e6-9807-90ba2519a270.png)

Koraci za reproduciranje problema:
1. Login kao šef (username: anogo; password an)
2. Klik na button "Pregled vozača"
3. Klik na unesenog vozača (bez ikakvih vožnji/aktivnosti bez ičega)
4. Klik na dugme "Prikaz aktivnosti"

Dobijeni rezultat: 
Unhandeled exception

Očekivani rezultat:
Ispis aktivnosti za odabranog vozača/obavijest da nije bilo aktivnosti za tog vozača.

**Comment by IrmaKarasoftic** [comment]
#30

**Comment by alicajla** [comment]
Nije baš duplikat, jer u issue-u #30 Admira piše o situaciji kada NIJE selektovan ni jedan vozač, a moj se odnosi na situaciju kada je selektovan vozač koji se nalazi u sistemu.

**Comment by anogo1** [comment]
u #31 je opisano kada je selektovan vozac
