### ISSUE TITLE
Labela nije u potpunosti vidljiva

### ISSUE THREAD

**Issue by alicajla** [SoftverInzenjeringETFSA/SI2015Tim7#80]
Komponenta: Odjavljivanje preuzetog vozila /  Izvještaji

Commit ID: [e26a9d8](https://github.com/SoftverInzenjeringETFSA/SI2015Tim7/commit/e26a9d8053d3050c71a3204378d68e1e86eec2ae)  

Opis problema: Labela nije vidljiva u potpunosti - [Slika](http://prntscr.com/b6aww8)
Naziv buttona u potpunosti nije vidljiv - [Slika](http://prntscr.com/b6h002)

Koraci za reproduciranje problema:
1. Login kao vozač (username: ajdinm; password: am)
2. Klik na button "Odjava preuzetog vozila"
Koraci za reproduciranje problema:
1. Login kao šef (username anogo; password: an)
2. Klik na button "Izvještaji"

Dobijeni rezultat: 
Otvorena forma

Očekivani rezultat:
Labela: "Cijena go..." nije u potpunosti vidljiva (predpostavljam da treba pisati cijena goriva)
Naziv buttona: "Izvještaj o aktivnostima vo..." nije u potpunosti vidljiv

**Comment by anogo1** [comment]
besmislen bug
