### ISSUE TITLE
Validacija na formi Prijavljivanje preuzetog vozila

### ISSUE THREAD

**Issue by alicajla** [SoftverInzenjeringETFSA/SI2015Tim7#83]
Komponenta: Prijavljivanje preuzetog vozila

Commit ID: [e26a9d8](https://github.com/SoftverInzenjeringETFSA/SI2015Tim7/commit/e26a9d8053d3050c71a3204378d68e1e86eec2ae)  

Opis problema: Nisu validirana potrebna polja

Koraci za reproduciranje problema:
1. Login kao vozač (username: ajdinm; password am)
2. Klik na button "Prijava preuzetog vozila"

Dobijeni rezultat: 
Otvorena forma, moguće dodati vozilo

Očekivani rezultat:
Poruka o pogrešno unesenim parametrima / nedostatak validacije svih polja

**Comment by anogo1** [comment]
#27
