### ISSUE TITLE
Neusaglašenost sistema i UIS-a 5.3.11. i 5.3.12.

### ISSUE THREAD

**Issue by alicajla** [SoftverInzenjeringETFSA/SI2015Tim7#96]
Komponenta: Izvještaj / Izvještaj o aktivnostima vozača i Izvještaj o odabranom vozilu

Commit ID: e26a9d8

Opis problema: Neispravno implementirana funkcionalnost 5.3.11./5.3.12.
U UIS-u ste naveli: [Slika](http://prnt.sc/b6hmk6), odnosno: [Slika](http://prntscr.com/b6hoyp), međutim, logika ovog izvještaja skroz je promijenjena - nema biranja vozača, nema generisanja izvještaja na osnovu odabranog vozača (šta će se desiti u vašem slučaju ako dva vozača imaju isto ime i prezime? Nije nerealna situacija, u gradu ja znam za bar 5 djevojaka koje se zovu i prezivaju kao ja - ako mi ne vjerujete -> bhTelecom imenik i uvjerit ćete se)

Koraci za reproduciranje problema:
1. Login kao šef (username: anogo; password an)
2. Klik na button "Izvještaji"
3. Klik na button "Izvještaj o aktivnostima vozača"/Izvještaj o vozilima

Dobijeni rezultat:
Nema rezultata

Očekivani rezultat: 
Implementacija prema napisanom/nacrtanom toku u UIS-u.

**Comment by anogo1** [comment]
#90
