### ISSUE TITLE
Nije ispunjen zahtjev klijenta (iz intervjua) 6.

### ISSUE THREAD

**Issue by alicajla** [SoftverInzenjeringETFSA/SI2015Tim7#97]
Komponenta: Odjavljivanje preuzetog vozila

Commit ID: e26a9d8

Opis problema: Nije implementiran dio funkcionalnosti koju je zahtjevao korisnik.
U intervjuu piše: [Slika](http://prnt.sc/b6ht1h), međutim, omogućili ste samo jedno polje pod nazivom gorivo koje je opcionalno i nije nimalo intuitivno (u smislu da vozač ne zna koje sve podatke mora ukucati - da li je sipao gorivo, koliko litara i za koliko novca?)

Koraci za reproduciranje problema:
1. Login kao vozač (username: dinom; password dm)
2. Klik na button "Odjavljivanje preuzetog vozila"

Dobijeni rezultat:
Nema rezultata

Očekivani rezultat: 
Implementacija prema klijentovim zahtjevima iz intervjua.

**Comment by anogo1** [comment]
http://pokit.org/get/?a5b7ffebcd6596ed638734719ffe2d02.png
ukoliko nije sipao gorivo, dovoljno je da unese 0 u ova dva polja koja su vezana za gorivo, ukoliko je pak sipao gorivo, onda unosi podatkeu odgovarajuće polje
