### ISSUE TITLE
Neispunjen zahtjev klijenta iz Intervjua 7.1.

### ISSUE THREAD

**Issue by alicajla** [SoftverInzenjeringETFSA/SI2015Tim7#98]
Komponenta: Servis

Commit ID: e26a9d8

Opis problema: Nije implementiran dio funkcionalnosti koju je zahtjevao korisnik.
U intervjuu piše: [Slika](http://prnt.sc/b6hvg8), međutim, nije omogućeno šefu mijenjanje statusa vozila; samim tim je unos cijene servisiranja nije urađen po klijentovim zahtjevima.

Koraci za reproduciranje problema:
1. Login kao šef (username: anogo; password an)
2. Klik na button "Servis"
3. Tab Odjava vozila sa servisa

Dobijeni rezultat:
Nema rezultata

Očekivani rezultat: 
Implementacija prema klijentovim zahtjevima iz intervjua.

**Comment by anogo1** [comment]
ukoliko je šef odjavio vozilo sa servisa, sistem sam postavlja status vozila na slobodno, nema potrebe da šef ručno mijenja status(to bi čak dovelo do situacije da on odjavljuje vozilo sa servisa, a da zaboravi promijeniti status, te da se vozilo idalje vodi u sistemu kao da je na servisu)
prilikom odjave sa servisa je omogućen unos cijene servisiranja
http://pokit.org/get/?8f9daef5167ca457b29dd29ef37b6f8b.png
